language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t narquette/docker-react-2 -f Dockerfile.dev .

script:
  - docker run -e CI=true narquette/docker-react-2 npm run test